# DON'T REMOVE THIS FILE.
# This file is for render site varibles and plugins
# The actual configuration files are stored in the `config/_default/` folder.

######################### site variables ##############################
# customize your color and font from here.
[params.variables]
color_primary = "#41228e"
color_secondary = "#2bfdff"
body_color = "#fff"
border_color = "#c7c7c7"
black = "#000"
white = "#fff"
light = "#eee"
gray = "#eaeaea"
text_color = "#4c4c4c"
text_dark = "#000"
text_light = "#999999"

# font variables
# base font size for full website,
font_size = "16px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.25" # default is "majorThird": 1.25

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.
# example: "Work+Sans:wght@400;500;600"
font_icon = "themify" # https://themify.me/themify-icons
font_primary = "Montserrat:wght@400;500;600"
font_primary_type = "sans-serif" # [serif/sans-serif]
font_secondary = "Outfit:wght@700;800;900"
font_secondary_type = "sans-serif" # [serif/sans-serif]

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/themify-icons/icons.css"
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
[[params.plugins.css]]
link = "https://unpkg.com/aos@2.3.1/dist/aos.css"
[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/npm/glightbox@3.2.0/dist/css/glightbox.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/cookie.js"
[[params.plugins.js]]
link = "plugins/lazy-loader.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"
[[params.plugins.js]]
link = "https://unpkg.com/aos@2.3.1/dist/aos.js"
attributes = "defer"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/parallax.js/1.5.0/parallax.min.js"
attributes = "defer"
[[params.plugins.js]]
link = "https://cdn.jsdelivr.net/npm/glightbox@3.2.0/dist/js/glightbox.min.js"
attributes = "defer"